import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@/app/globals.css';

const poppins = Poppins({
  weight: '900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  footer,
}: Readonly<{
  children: React.ReactNode;
  footer: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {children}
        {footer}
      </body>
    </html>
  );
}
